apiVersion: v1
kind: Pod
metadata:
  labels:
    name: simple-webapp
  name: simple-webapp-2
  namespace: default
spec:
  containers:
  - env:
    - name: APP_START_DELAY
      value: "120"
    image: meramsform/webapp-probes
    name: simple-webapp
    ports:
    - containerPort: 8080
      protocol: TCP
