apiVersion: v1
kind: replicaSet
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        tier: webapp
    spec:
      containers:
      name: webapp
        image: nginx:not-good
