apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: webapp
      image: httpd
      env:
        - name: NOM
          value: "Mon Nom"
        - name: PRENOM
          value: "Mon Prenom"
        - name: AGE
          value: "20"
