apiVersion: v1
kind: Service
metadata:
  labels:
    tier: back
    bu: finance
  name: back-fin
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    tier: back
    bu: finance
  type: ClusterIP
