apiVersion: v1
kind: Service
metadata:
  labels:
    tier: front
    bu: finance
  name: front-fin
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    tier: front
    bu: finance
  type: ClusterIP
