apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-3
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu
    securityContext:
      runAsUser: 1001
  - command:
    - sleep
    - "4800"
    image: nginx
    name: nginx
    securityContext:
      runAsUser: 1002
