apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: meramsform/rollout:1.0
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /opt/app/ready.sh
